### ISSUE TITLE
No model despite +model

### ISSUE THREAD

**Issue by qOEJXOT4** [uuverifiers/princess#10]
Hi, princess does not return a concrete model/witness for me despite providing `+model`.

I omitted the formula from the request because I don't know if I am allowed to provide it.
Hope it's straightforward to see in the princess code why there could potentially be missing the concrete model, otherwise I can ask if the formula is safe to share.
```
{
"options" : ["-inputFormat=pri", "-quiet", "+model"],
"formula" : "\\existentialConstants { nat x_0, x_1, x_2; }\\problem { [omitted] }"
}
```
The result is:
```
{
    "result": "VALID\n\nUnder the constraint:\nx_2 = 2*x_0 & x_1 = 0\n"
}
```

Interestingly enough I get a concrete model when providing `-clausifier=simple` in some cases. Then I get:
```
{
    "result": "VALID\n\nUnder the constraint:\n(x_2 = 2*x_0 & x_1 = 0 & x_0 >= 3) | (x_2 = 2*x_0 & x_1 = 0 & x_0 >= 2) | (x_2 = 2 & x_1 = 0 & x_0 = 1) | (x_2 = 0 & x_1 = 0 & x_0 = 0)\n\nConcrete witness:\nx_2 = 6 & x_1 = 0 & x_0 = 3\n"
}
```
---
I also cannot access the maven repository:
```
<repositories>
    <repository>
        <id>uuverifiers</id>
        <name>uuverifiers</name>
        <url>http://logicrunch.research.it.uu.se/maven/</url>
    </repository>
</repositories>
```
Is it currently offline? I tried with `https` as well but then its redirecting me to another page.

**Comment by pruemmer** [comment]
Thanks for the report; I found and hopefully fixed this bug!

The URL of our Maven server changed a couple of days ago, it is now

https://eldarica.org/maven

**Comment by qOEJXOT4** [comment]
Thank you for the quick fix. In the webinterface its working for me :+1: .

When using the new maven repository it seems like the version provided by `nightly-SNAPSHOT` is not the current state of this GitHub repository.

I am using this:
```
<dependency>
    <groupId>uuverifiers</groupId>
    <artifactId>princess_2.13</artifactId>
    <version>nightly-SNAPSHOT</version>
</dependency>
```
```
<repositories>
    <repository>
        <id>uuverifiers</id>
        <name>uuverifiers</name>
        <url>https://eldarica.org/maven/</url>
    </repository>
</repositories>
```

but still get the same output without the model. I have cleared the `.m2` cache to make sure that the current files are fetched.

**Comment by pruemmer** [comment]
You are right, there was a git push missing. Does it work now?

**Comment by qOEJXOT4** [comment]
> You are right, there was a git push missing. Does it work now?

Yes, thank you very much. Everything is working now.
